export const WORD_BANK = {
    A: ["APPLE", "ASTRONAUT", "ARCHITECTURE", "ADMINISTRATION", "ALPHABET"],
    B: ["BANANA", "BUTTERFLY", "BIBLIOGRAPHER", "BIODEGRADABLE", "BREAKTHROUGH"],
    C: ["CHOCOLATE", "CHARACTERISTIC", "COMMUNICATION", "COMPREHENSIVE", "CIRCUMFERENCE"],
    D: ["DINOSAUR", "DISORIENTATION", "DOCUMENTATION", "DIFFERENTIATE", "DEVELOPMENTAL"],
    E: ["ECLIPSE", "ENVIRONMENTAL", "EXTRAORDINARY", "ENTHUSIASTIC", "ELECTROMAGNET"],
    F: ["FLAMINGO", "FOUNDATIONALLY", "FLUORESCENCE", "FRANKENSTEIN", "FEASIBILITY"],
    G: ["GIRAFFE", "GENERALIZATION", "GEOMETRICALLY", "GLOBALIZATION", "GRAVITATIONAL"],
    H: ["HURRICANE", "HISTORICALITY", "HYPERACTIVITY", "HUMANITARIAN", "HYDROPOWERED"],
    I: ["ILLUSION", "INTERNATIONAL", "IMPLEMENTATION", "IDENTIFICATION", "INFRASTRUCTURE"],
    J: ["JELLYFISH", "JUXTAPOSITION", "JOURNALISTIC", "JURISDICTION", "JUSTIFICATION"],
    K: ["KANGAROO", "KITCHENETTE", "KINETICALLY", "KALEIDOSCOPE", "KNOWLEDGEABLE"],
    L: ["LIGHTNING", "LABORATORIES", "LONGITUDINAL", "LUMINESCENCE", "LEXICOGRAPHY"],
    M: ["MOUNTAIN", "METAMORPHOSIS", "MULTIPLICATION", "MICROORGANISM", "MISUNDERSTAND"],
    N: ["NAVIGATOR", "NEUROSCIENCE", "NOTIFICATION", "NATIONALIZATION", "NEUTRALIZATION"],
    O: ["OCTOPUS", "ORGANIZATION", "OVERWHELMING", "ORTHOGONALITY", "OPTIMIZATION"],
    P: ["PHOENIX", "PHOTOGRAPHY", "PERSONALITY", "PARALLELOGRAM", "PRESERVATION"],
    Q: ["QUANTUM", "QUALIFICATION", "QUESTIONNAIRE", "QUANTIFICATION", "QUADRILATERAL"],
    R: ["RAINBOW", "RECOMMENDATION", "REVOLUTIONARY", "REPRESENTATION", "REORGANIZATION"],
    S: ["SURVIVAL", "SPECIFICATION", "SUBSTANTIALITY", "SUPERCONDUCTOR", "SYNCHRONIZATION"],
    T: ["TELESCOPE", "TRANSFORMATION", "TRANSPORTATION", "TELECOMMUNICATION", "THERMODYNAMICS"],
    U: ["UNICORN", "UNBELIEVABLE", "UNDERSTANDING", "UNIFICATION", "UNIVERSALLY"],
    V: ["VOLCANO", "VULNERABILITY", "VISUALIZATION", "VACUUMING", "VERIFICATION"],
    W: ["WATERFALL", "WEATHERPROOF", "WILDERNESSES", "WORKMANSHIP", "WAVELENGTHS"],
    X: ["XYLOPHONE", "XENOPHOBICALLY", "XEROGRAPHICALLY", "XENOTRANSPLANT"],
    Y: ["YESTERDAY", "YELLOWISHNESS", "YIELDINGLY", "YOTTABYTES"],
    Z: ["ZUCCHINI", "ZOOLOGICAL", "ZEALOUSNESS", "ZIGZAGGINGLY"]
};

export function IS_VALID_WORD(word) {
    if (!word) return false;
    const cleanWord = word.trim().toUpperCase();
    const firstLetter = cleanWord[0];
    const letterList = WORD_BANK[firstLetter];
    
    // Checks if list exists and word is at least 2 characters long
    return cleanWord.length >= 2 && letterList && letterList.some(w => w.startsWith(firstLetter));
}
