export const WORD_BANK = {
    A: ["ANTIDISESTABLISHMENTARIANISM", "AUTOBIOGRAPHICAL", "ADMINISTRATIVE", "ACCOMMODATIONS", "ASTRONAUTICAL", "AUTHENTICITIES"],
    B: ["BIBLIOGRAPHICAL", "BIODEGRADABILITY", "BIOTECHNOLOGY", "BREAKTHROUGHS", "BALLISTOCARDIOGRAM", "BUSINESSWOMAN"],
    C: ["CHARACTERIZATION", "COMPREHENSIVENESS", "COUNTERPRODUCTIVE", "CONSTITUTIONALITY", "CIRCUMNAVIGATION", "COMPATIBILITIES"],
    D: ["DISPROPORTIONATE", "DISAUTHENTICATE", "DOCUMENTATIONS", "DECONTAMINATION", "DISDIFERENTIATION", "DEVELOPMENTALLY"],
    E: ["ELECTROENCEPHALOGRAM", "ENVIRONMENTALIST", "EXTRAORDINARILY", "ELECTROMAGNETIC", "ENTREPRENEURSHIP", "EQUIPOTENTIALITY"],
    F: ["FORETHOUGHTFULNESS", "FUTURISTICALLY", "FOUNDATIONALISM", "FLUORESCENCES", "FINGERPRINTING", "FRACTIONALIZATION"],
    G: ["GASTROENTEROLOGY", "GENERALIZATIONS", "GRAVITATIONALLY", "GEOMORPHOLOGICAL", "GRANDFATHERLAND", "GIGANTISTRACAN"],
    H: ["HISTOPATHOLOGICAL", "HYPERPOPULARITY", "HUMANITARIANISM", "HETEROGENEITIES", "HYDRODYNAMICALLY", "HYPERVENTILATE"],
    I: ["INTERNATIONALIZATION", "INDISTINGUISHABLE", "IMPLEMENTATIONS", "INFRASTRUCTURES", "INDIVIDUALISTIC", "INTERACTIONISM"],
    J: ["JUXTAPOSITIONALLY", "JOURNALISTICALLY", "JURISDICTIONAL", "JUSTIFIABILITIES", "JUDICIOUSNESSES", "JAPANIZATION"],
    K: ["KALEIDOSCOPICALLY", "KNOWLEDGEABILITY", "KEYBOARDISTICALLY", "KILOMETRICALLY", "KINESIOLOGICAL", "KINDERGARTENERS"],
    L: ["LEXICOGRAPHICALLY", "LUMINESCENCES", "LABORATORISTIC", "LONGITUDINALLY", "LITHOGRAPHICAL", "LOCOMOTIVELY"],
    M: ["MICROORGANISMS", "MULTIDIMENSIONAL", "MISUNDERSTANDING", "MAGNETOSPHERIC", "METAMORPHOSISM", "MANUFACTURING"],
    N: ["NEUROTRANSMITTER", "NATIONALIZATION", "NEUROBIOLOGICAL", "NONCONFIGURABLE", "NOTIFIKATIONALLY", "NONCHALANTLY"],
    O: ["ORGANIZATIONAL", "OVERWHELMINGLY", "ORTHOGONALITIES", "OSTEOPOROSISES", "OPPORTUNISTICALLY", "OVEREXTENSION"],
    P: ["PNEUMONOULTRAMICROSCOPICSILICOVOLCANOCONIOSIS", "PHOTOGRAPHICAL", "PARALLELOGRAMS", "PSYCHOPERCEPTUAL", "PHARMACEUTICAL"],
    Q: ["QUALIFICATIONAL", "QUANTIFICATIONAL", "QUADRILATERALS", "QUESTIONNAIRES", "QUINTESSENTIAL", "QUATERCENTENARY"],
    R: ["RECOMMENDATIONS", "REVOLUTIONARIES", "REPRESENTATIONAL", "REHABILITATION", "REORGANIZATIONS", "RADIOACTIVITY"],
    S: ["SUPERCALIFRAGILISTICEXPIALIDOCIOUS", "SPECTROPHOTOMETRY", "SUBSTANTIATION", "SYNCHRONIZATION", "STRATOSPHERIC"],
    T: ["TELECOMMUNICATIONS", "TRANSFORMATIONAL", "THERMODYNAMICAL", "TRANSCENDENTAL", "TRANSPORTATIONS", "TECHNOLOGICAL"],
    U: ["UNCHARACTERISTIC", "UNCONSTITUTIONAL", "UNDERSTANDABLE", "UNFORGIVABLY", "UNPREDICTABILITY", "UNIVERSALITIES"],
    V: ["VALITUDINARIAN", "VENTILATIONALLY", "VULNERABILITIES", "VISUALIZATIONS", "VOLCANOLOGICALLY", "VERTICALITY"],
    W: ["WEATHERPROOFING", "WAVELENGTHWISE", "WORKMANSHIPS", "WEATHERSTRIPPING", "WATERPROOFINGS", "WESTERNIZATION"],
    X: ["XENOTRANSPLANTATION", "XEROGRAPHICALLY", "XYLOPTOGRAPHIC", "XENOPHOBICALLY", "XERORADIOGRAPHY", "XENODIAGNOSIS"],
    Y: ["YESTERYEARS", "YOUTHfulnesses", "YELLOWISHNESSES", "YIELDINGNESS", "YOTTABYTES", "YOUTHFULLY"],
    Z: ["ZOOLOGICAL", "ZEALOUSNESSES", "ZIGZAGGINGLY", "ZOOPLANKTONIC", "ZIRCONIUMS", "ZEROIZATION"]
};

const EXPANDED_DICTIONARY = new Set([
    "A", "ABLE", "ABOUT", "ABSOLUTE", "ABSOLUTELY", "ACCOMMODATION", "ACCOMMODATIONS", "ADMINISTRATION", "ADMINISTRATIVE", "ALPHABET", "ALPHABETICAL", "ANCHOR", "ANIMAL", "ANT", "ANTIDISESTABLISHMENTARIANISM", "APPLE", "ARCHITECTURE", "ASTRONAUT", "ASTRONAUTICAL", "AUTHENTICITY", "AUTHENTICITIES", "AUTOBIOGRAPHICAL", "AVOCADO",
    "BALL", "BALLOON", "BANANA", "BEAR", "BENEFICIARY", "BICYCLE", "BIBLIOGRAPHER", "BIBLIOGRAPHICAL", "BIODEGRADABLE", "BIODEGRADABILITY", "BIOTECHNOLOGY", "BLOOMINGTON", "BRIDGE", "BUILDING", "BUTTERFLY", "BALLISTOCARDIOGRAM", "BARRICADING", "BREAKTHROUGH", "BREAKTHROUGHS", "BUSINESSWOMAN",
    "CAMERA", "CASTLE", "CAT", "CHARACTERISTIC", "CHARACTERIZATION", "CHEESE", "CHOCOLATE", "CHRONOLOGICAL", "CIRCUMFERENCE", "CIRCUMNAVIGATION", "CLOUD", "COMPUTER", "COMPATIBILITIES", "COMPREHENSIVE", "COMPREHENSIVENESS", "CONSTITUTIONALITY", "CONSTRUCTIVE", "COUNTERPRODUCTIVE", "CUBE",
    "DECONTAMINATION", "DESK", "DEVELOPMENTAL", "DEVELOPMENTALLY", "DIAMOND", "DIFFERENTIATE", "DINOSAUR", "DISAUTHENTICATE", "DISDIFERENTIATION", "DISPLACEMENT", "DISORIENTATION", "DISPROPORTIONATE", "DOCUMENTATION", "DOCUMENTATIONS", "DOG", "DOLPHIN", "DOMINO", "DOOR", "DRAGON", "DREAM",
    "EAGLE", "EARTH", "ECLIPSE", "ELECTROENCEPHALOGRAM", "ELECTROMAGNET", "ELECTROMAGNETIC", "ELEPHANT", "EMERALD", "ENERGY", "ENGINE", "ENTHUSIASTIC", "ENTREPRENEURSHIP", "ENVIRONMENTAL", "ENVIRONMENTALIST", "EQUALIZATION", "EQUIPOTENTIALITY", "EXEMPLIFICATION", "EXPLORER", "EXTRAORDINARY", "EXTRAORDINARILY",
    "FALCON", "FEATHER", "FEASIBILITY", "FIRE", "FISH", "FLAMINGO", "FLUORESCENCE", "FLUORESCENCES", "FOREST", "FORETHOUGHTFULNESS", "FOUNDATIONALLY", "FOUNDATIONALISM", "FOUNTAIN", "FRACTIONATION", "FRACTIONALIZATION", "FRANKENSTEIN", "FUTURES", "FUTURISTICALLY", "FINGERPRINTING",
    "GALAXY", "GARDEN", "GASTROENTEROLOGY", "GENERALIZATION", "GENERALIZATIONS", "GENEROSITY", "GEOMETRICALLY", "GEOMORPHOLOGICAL", "GIGANTISTRACAN", "GIRAFFE", "GLACIER", "GLOBALIZATION", "GOBLIN", "GOLDFISH", "GORILLA", "GRANDFATHERED", "GRANDFATHERLAND", "GRAVITATIONAL", "GRAVITATIONALLY", "GUITAR",
    "HAMMER", "HAMSTER", "HELMET", "HETEROGENEOUS", "HETEROGENEITIES", "HEURISTICALLY", "HIGHWAY", "HISTORICALITY", "HISTOPATHOLOGICAL", "HORIZON", "HORSE", "HOUSE", "HUMANITARIAN", "HUMANITARIANISM", "HURRICANE", "HYDRODYNAMICALLY", "HYDROPOWERED", "HYPERACTIVITY", "HYPERPOPULARITY", "HYPERVENTILATE",
    "ICEBERG", "IDENTIFICATION", "IGLOO", "IGUANA", "ILLUSION", "IMPLEMENTATION", "IMPLEMENTATIONS", "IMPRESSIONISM", "INDIVIDUALITY", "INDIVIDUALISTIC", "INDISTINGUISHABLE", "INFINITY", "INFRASTRUCTURE", "INFRASTRUCTURES", "INSECT", "INTERACTIONISM", "INTERNATIONAL", "INTERNATIONALIZATION", "ISLAND", "IVORY",
    "JACKET", "JAGUAR", "JAVELIN", "JELLYFISH", "JEWELRY", "JEWELRYMAKING", "JAPANIZATION", "JOURNAL", "JOURNALISTIC", "JOURNALISTICALLY", "JUDICIOUSLY", "JUDICIOUSNESSES", "JUNGLE", "JUPITER", "JURISDICTION", "JURISDICTIONAL", "JUSTIFICATION", "JUSTIFIABILITIES", "JUXTAPOSITION", "JUXTAPOSITIONALLY",
    "KALEIDOSCOPE", "KALEIDOSCOPICALLY", "KANGAROO", "KEYBOARD", "KEYBOARDISTICALLY", "KILOMETRAGE", "KILOMETRICALLY", "KINDERGARTENERS", "KINESIOLOGICAL", "KINETICALLY", "KING", "KINGDOM", "KITCHEN", "KITCHENETTE", "KITE", "KNIGHT", "KNOWLEDGEABLE", "KNOWLEDGEABILITY", "KOALA",
    "LABORATORIES", "LABORATORISTIC", "LANTERN", "LAVA", "LEMON", "LEOPARD", "LEXICOGRAPHY", "LEXICOGRAPHICALLY", "LIBRARY", "LIGHTNING", "LION", "LIQUIDATION", "LITHOGRAPHICAL", "LIZARD", "LOCOMOTIONAL", "LOCOMOTIVELY", "LONGITUDINAL", "LONGITUDINALLY", "LUMINESCENCE", "LUMINESCENCES",
    "MACHINE", "MAGNET", "MAGNETOSPHERE", "MAGNETOSPHERIC", "MANUFACTURING", "METAMORPHOSIS", "METAMORPHOSISM", "METEOR", "MICROORGANISM", "MICROORGANISMS", "MISUNDERSTAND", "MISUNDERSTANDING", "MONKEY", "MONSTER", "MONUMENTALLY", "MOONLIGHT", "MOUNTAIN", "MULTIDIMENSIONAL", "MULTIPLICATION", "MUSEUM",
    "NATIONALIZATION", "NATURE", "NAVIGATIONALLY", "NAVIGATOR", "NEBULA", "NEEDLE", "NEST", "NEUROBIOLOGICAL", "NEUROSCIENCE", "NEUROTRANSMITTER", "NEUTRALIZATION", "NIGHT", "NINJA", "NONCHALANTLY", "NONCONFIGURABLE", "NOTEBOOK", "NOTIFICATION", "NOTIFIKATIONALLY",
    "OCEAN", "OCTOPUS", "OPPORTUNISTIC", "OPPORTUNISTICALLY", "OPTIMIZATION", "ORANGE", "ORBIT", "ORCHESTRA", "ORGANIZATION", "ORGANIZATIONAL", "ORTHOGONALITY", "ORTHOGONALITIES", "OSTEOPOROSISES", "OSTRICH", "OUTSTANDINGLY", "OVEREXTENSION", "OVERWORLD", "OVERWHELMING", "OVERWHELMINGLY", "OWL",
    "PALACE", "PANTHER", "PARALLELOGRAM", "PARALLELOGRAMS", "PENGUIN", "PERSONALITY", "PHARMACEUTICAL", "PHOENIX", "PHOTOGRAPHY", "PHOTOGRAPHICAL", "PILLAR", "PIRATE", "PLANET", "PNEUMONOULTRAMICROSCOPICSILICOVOLCANOCONIOSIS", "PRESERVATION", "PROFESSIONAL", "PSYCHOLOGICAL", "PSYCHOPERCEPTUAL", "PYRAMID",
    "QUAD", "QUADRILATERAL", "QUADRILATERALS", "QUALIFICATION", "QUALIFICATIONAL", "QUALIFIED", "QUALITATIVELY", "QUANTIFICATION", "QUANTIFICATIONAL", "QUANTUM", "QUARTZ", "QUASAR", "QUEEN", "QUEST", "QUESTIONNAIRE", "QUESTIONNAIRES", "QUICK", "QUINTESSENTIAL", "QUIVER", "QUATERCENTENARY",
    "RADAR", "RADIOACTIVITY", "RADIOLOGICAL", "RAINBOW", "RECOMMENDATION", "RECOMMENDATIONS", "REHABILITATE", "REHABILITATION", "REORGANIZATION", "REORGANIZATIONS", "REPRESENTATION", "REPRESENTATIONAL", "REPTILES", "REVOLUTIONARY", "REVOLUTIONARIES", "RHINO", "RIVER", "ROBOT", "ROCKET", "RUBY",
    "SAPPHIRE", "SATELLITE", "SHARK", "SPECTROPHOTOMETRY", "SPECIFICATION", "SPIDER", "STAR", "STORM", "STRATOSPHERE", "STRATOSPHERIC", "SUBSTANTIABILITY", "SUBSTANTIATION", "SUNFLOWER", "SUPERCALIFRAGILISTICEXPIALIDOCIOUS", "SUPERCONDUCTOR", "SURVIVAL", "SYNCHRONIZATION",
    "TECHNOLOGICAL", "TELECOMMUNICATION", "TELECOMMUNICATIONS", "TELESCOPE", "TEMPLE", "THERMODYNAMICS", "THERMODYNAMICAL", "TIGER", "TORNADO", "TOWER", "TRANSCENDENTAL", "TRANSFORMATION", "TRANSFORMATIONAL", "TRANSPORTATION", "TRANSPORTATIONS", "TREASURE", "TSUNAMI", "TURTLE",
    "ULTRA", "UMBRELLA", "UNBELIEVABLE", "UNCHARACTERISTIC", "UNCONDITIONAL", "UNCONSTITUTIONAL", "UNDERSTANDING", "UNDERSTANDABLE", "UNFORGIVABLY", "UNIFICATION", "UNICORN", "UNIVERSALITIES", "UNIVERSALLY", "UNIVERSE", "UNPREDICTABLE", "UNPREDICTABILITY", "UPGRADE", "URANIUM", "URBAN", "UTENSIL",
    "VACUUMING", "VALUATIONALLY", "VALLEY", "VALITUDINARIAN", "VANILLA", "VELOCITY", "VENTILATIONS", "VENTILATIONALLY", "VERIFICATION", "VERTICALITY", "VIKING", "VIOLIN", "VISUALIZATION", "VISUALIZATIONS", "VOLCANO", "VOLCANOLOGICALLY", "VORTEX", "VULNERABILITY", "VULNERABILITIES", "VULTURE",
    "WALRUS", "WATERFALL", "WATERPROOFINGS", "WAVE", "WAVELENGTHS", "WAVELENGTHWISE", "WEAPON", "WEATHERPROOF", "WEATHERPROOFING", "WEATHERSTRIPPING", "WESTERNIZATION", "WHOLEHEARTED", "WILDERNESS", "WILDERNESSES", "WIZARD", "WOLF", "WORKMANSHIP", "WORKMANSHIPS", "WORLD",
    "XANTHOPHYLLS", "XENODIAGNOSIS", "XENOLITH", "XENON", "XENOPHOBICALLY", "XENOPUS", "XENOTRANSPLANT", "XENOTRANSPLANTATION", "XEROGRAPHICALLY", "XERORADIOGRAPHY", "XERUS", "XYLOGRAPHIES", "XYLOPHONE", "XYLOPTOGRAPHIC", "XRAY",
    "YACHT", "YAK", "YARD", "YEARBOOK", "YELLOW", "YELLOWISHNESS", "YELLOWISHNESSES", "YESTERDAY", "YESTERYEARS", "YETI", "YIELDINGLY", "YIELDINGNESS", "YOTTABYTES", "YOUTHfulness", "YOUTHfulnesses", "YOUTHFULLY", "YOUTHIFICATION", "YUCCA",
    "ZEALOUSNESS", "ZEALOUSNESSES", "ZEBRA", "ZERO", "ZEROIZATION", "ZIGZAGGINGLY", "ZINC", "ZIPPER", "ZIRCONIUMS", "ZODIAC", "ZOMBIE", "ZOOLOGICAL", "ZOOPLANKTON", "ZOOPLANKTONIC", "ZUCCHINI"
]);

export function IS_VALID_WORD(word) {
    if (!word || word.length === 0) return false;
    const firstLetter = word[0].toUpperCase();
    const list = WORD_BANK[firstLetter];
    return list ? list.includes(word.toUpperCase()) : false;
}
